version: '3.8'
services:
  db:
    image: postgres:17.2
    container_name: postgres_db
    environment:
      POSTGRES_DB: barber_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5432:5432"
    volumes:
      - .:/barber-shop:z
      - barber-shop-net